ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.16.1'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        pass_filenames: false
      - id: ruff-format
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell  # See pyproject.toml for args
        additional_dependencies:
          - tomli

  - repo: local
    hooks:
      - id: ty-check
        name: check type hints by ty
        entry: uv run --frozen ty check
        language: system
        pass_filenames: false
